### ISSUE TITLE
스프린트 1주기 - 프로젝트 기본 UI 설계

### ISSUE THREAD

**Issue by hin6150** [chalIengers/challengers-front#1]
스프린트 진행 기간 :  07/04 ~ 07/17 
스프린트 목표:  메인, 프로젝트, 프로젝트 상세, 프로젝트 생성 페이지 컴포넌트 및 레이아웃 UI 설계

개인 작업 목표

- [x] #2
- [x] 라우터 설정 
- [x] 프로젝트 Inner 컴포넌트
- [x] ButtonBox 컴포넌트
- [x] Text 컴포넌트
- [x] 추가 페이지 Layout 설정

**Comment by klmhyeonwoo** [comment]
Good~!
